[platformio]
src_dir = triton_ota
default_envs = triton_io

[env:triton_io]
platform  = espressif32
board     = esp32dev
framework = arduino

board_build.partitions = triton_ota/partitions.csv

lib_deps =
    bblanchon/ArduinoJson@^6.21.4

monitor_speed = 115200
build_flags   = -DCORE_DEBUG_LEVEL=3
