# Convert a raw .iop object pool file (e.g. exported from AgIsoTerminalDesigner,
# https://open-agriculture.github.io/AgIsoTerminalDesigner/) into a C++ header
# VTObjectPool.cpp can embed via its VT_POOL_USE_DESIGNED_POOL toggle.
#
# Usage: .\tools\vt_pool\iop_to_header.ps1 <input.iop> [output.hpp]

param(
    [Parameter(Mandatory = $true)][string]$InputIop,
    [string]$OutputHpp
)

if (-not (Test-Path $InputIop)) {
    Write-Error "'$InputIop' not found"
    exit 1
}

if (-not $OutputHpp) {
    $OutputHpp = Join-Path $PSScriptRoot "generated\VTObjectPool_Designed.hpp"
}
New-Item -ItemType Directory -Force -Path (Split-Path $OutputHpp -Parent) | Out-Null

$bytes = [System.IO.File]::ReadAllBytes((Resolve-Path $InputIop))
if ($bytes.Length -eq 0) {
    Write-Error "'$InputIop' is empty"
    exit 1
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated by tools/vt_pool/iop_to_header.ps1 -- do not hand-edit.")
$lines.Add("// Source: $(Split-Path $InputIop -Leaf) ($($bytes.Length) bytes)")
$lines.Add("#pragma once")
$lines.Add("#include <stdint.h>")
$lines.Add("")
$lines.Add("namespace triton {")
$lines.Add("")
$lines.Add("static const uint8_t kDesignedPool[] = {")
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $chunk = $bytes[$i..([Math]::Min($i + 15, $bytes.Length - 1))]
    $hex = ($chunk | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    $lines.Add("    $hex,")
}
$lines.Add("};")
$lines.Add("static const uint32_t kDesignedPoolSize = sizeof(kDesignedPool);")
$lines.Add("")
$lines.Add("}  // namespace triton")

Set-Content -Path $OutputHpp -Value $lines -Encoding ASCII
Write-Host "Wrote $($bytes.Length) bytes as $OutputHpp"
